CREATE TABLE IF NOT EXISTS stock_daily_bar (
    stock_code VARCHAR(20) NOT NULL,
    trade_date DATE NOT NULL,
    open_price DECIMAL(12, 4) NOT NULL,
    close_price DECIMAL(12, 4) NOT NULL,
    high_price DECIMAL(12, 4) NOT NULL,
    low_price DECIMAL(12, 4) NOT NULL,
    volume DECIMAL(20, 2) DEFAULT NULL,
    amount DECIMAL(20, 2) DEFAULT NULL,
    change_rate DECIMAL(12, 6) DEFAULT NULL,
    adjust_type VARCHAR(10) NOT NULL DEFAULT 'qfq',
    data_source VARCHAR(32) NOT NULL DEFAULT 'akshare_eastmoney',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (stock_code, trade_date),
    KEY idx_stock_daily_bar_trade_date (trade_date)
);

CREATE TABLE IF NOT EXISTS stock_signal_event (
    event_id BIGINT NOT NULL AUTO_INCREMENT,
    stock_code VARCHAR(20) NOT NULL,
    stock_name VARCHAR(50) DEFAULT NULL,
    signal_date DATE NOT NULL,
    event_scope VARCHAR(20) NOT NULL DEFAULT 'day',
    increase_count INT NOT NULL DEFAULT 0,
    increase_amount DECIMAL(20, 2) NOT NULL DEFAULT 0,
    increase_ratio_sum DECIMAL(12, 6) NOT NULL DEFAULT 0,
    increase_ratio_max DECIMAL(12, 6) NOT NULL DEFAULT 0,
    changer_count INT NOT NULL DEFAULT 0,
    changer_names VARCHAR(2000) DEFAULT NULL,
    position_tags VARCHAR(1000) DEFAULT NULL,
    has_same_day_decrease TINYINT(1) NOT NULL DEFAULT 0,
    same_day_decrease_amount DECIMAL(20, 2) NOT NULL DEFAULT 0,
    consecutive_increase_days INT NOT NULL DEFAULT 1,
    signal_score INT NOT NULL DEFAULT 0,
    event_version INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id),
    UNIQUE KEY uk_stock_signal_event (stock_code, signal_date, event_scope),
    KEY idx_stock_signal_event_signal_date (signal_date),
    KEY idx_stock_signal_event_signal_score (signal_score)
);

CREATE TABLE IF NOT EXISTS stock_backtest_metric (
    event_id BIGINT NOT NULL,
    horizon_days INT NOT NULL,
    entry_date DATE NOT NULL,
    entry_price DECIMAL(12, 4) NOT NULL,
    entry_price_type VARCHAR(20) NOT NULL DEFAULT 'next_open',
    exit_date DATE NOT NULL,
    exit_price DECIMAL(12, 4) NOT NULL,
    return_pct DECIMAL(12, 6) NOT NULL,
    max_return_pct DECIMAL(12, 6) NOT NULL,
    max_drawdown_pct DECIMAL(12, 6) NOT NULL,
    volatility_pct DECIMAL(12, 6) DEFAULT NULL,
    hit_3pct_flag TINYINT(1) NOT NULL DEFAULT 0,
    hit_5pct_flag TINYINT(1) NOT NULL DEFAULT 0,
    hit_10pct_flag TINYINT(1) NOT NULL DEFAULT 0,
    is_positive_flag TINYINT(1) NOT NULL DEFAULT 0,
    bars_count INT NOT NULL DEFAULT 0,
    calc_version INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id, horizon_days),
    KEY idx_stock_backtest_metric_horizon (horizon_days)
);

CREATE TABLE IF NOT EXISTS stock_backtest_summary (
    stock_code VARCHAR(20) NOT NULL,
    stock_name VARCHAR(50) DEFAULT NULL,
    sample_event_count INT NOT NULL DEFAULT 0,
    win_rate_5d DECIMAL(12, 6) DEFAULT NULL,
    win_rate_10d DECIMAL(12, 6) DEFAULT NULL,
    win_rate_20d DECIMAL(12, 6) DEFAULT NULL,
    avg_return_5d DECIMAL(12, 6) DEFAULT NULL,
    avg_return_10d DECIMAL(12, 6) DEFAULT NULL,
    avg_return_20d DECIMAL(12, 6) DEFAULT NULL,
    median_return_20d DECIMAL(12, 6) DEFAULT NULL,
    avg_max_drawdown_20d DECIMAL(12, 6) DEFAULT NULL,
    hit_5pct_rate_20d DECIMAL(12, 6) DEFAULT NULL,
    hit_10pct_rate_60d DECIMAL(12, 6) DEFAULT NULL,
    historical_response_score INT NOT NULL DEFAULT 0,
    backtest_score INT NOT NULL DEFAULT 0,
    last_event_date DATE DEFAULT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (stock_code),
    KEY idx_stock_backtest_summary_score (backtest_score)
);

CREATE TABLE IF NOT EXISTS backtest_job_log (
    job_id BIGINT NOT NULL AUTO_INCREMENT,
    job_type VARCHAR(50) NOT NULL,
    run_mode VARCHAR(20) NOT NULL,
    run_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    affected_stock_count INT NOT NULL DEFAULT 0,
    fetched_bar_count INT NOT NULL DEFAULT 0,
    event_count INT NOT NULL DEFAULT 0,
    metric_count INT NOT NULL DEFAULT 0,
    error_message TEXT DEFAULT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME DEFAULT NULL,
    PRIMARY KEY (job_id),
    KEY idx_backtest_job_log_run (job_type, run_date)
);
